Updated transformer
pedrolarben/ADLStream pull request #2
Opened 2021-05-17 18:16 UTC by preinaj

2021-05-26 15:02 UTC, pedrolarben requested changes
Thanks for the update :)
Check the comments for some minor-changes requests.

2021-05-26 15:02 UTC, pedrolarben commented on ADLStream/models/transformer.py
> +        attribute,
Add 'attribute' to the docstring.

2021-05-26 15:02 UTC, pedrolarben commented on ADLStream/models/transformer.py
> +            print("Shape del tar_inp: ",tar_inp.shape)
Please remove these prints

2021-05-26 15:02 UTC, pedrolarben commented on ADLStream/models/transformer.py
>          input_shape (tuple): Shape of the input data.
Sort the arguments of the docstring (Keep the same order as in the function).

2021-05-26 15:02 UTC, pedrolarben commented on ADLStream/models/transformer.py
> +        attribute (int): Index of the attribute that we want to predict, if the number of
Could it be a list of integers? (list of indices of the attributes to be used as the target)

2021-06-12 11:21 UTC, preinaj commented
I think i added the possibility of using multiples attributes instead of just one, in the case that you have different numbers of attributes in the output and input. I tried it with a couple of examples and i think it's working fine. However, when the experiments are done, I will check with a few more examples to see  if it is really everything alright.

2021-06-15 08:00 UTC, pedrolarben commented
Close PR because the last commit has affected to all the files. Please feel free to reopen it.

2021-06-15 08:00 UTC, closed without merging